[workspace]

members = [
  "bot",
  "azalea-client",
  "azalea-protocol",
  "azalea-chat",
  "azalea-core",
  "azalea-auth",
  "azalea-nbt",
  "azalea-brigadier",
  "azalea-crypto",
]

[profile.release]
debug = true

[profile.dev.package.azalea-crypto]
opt-level = 3
