[workspace]

members = [
  "bot",
  "azalea-client",
  "azalea-protocol",
  "azalea-chat",
  "azalea-core",
  "azalea-auth",
  "azalea-nbt",
  "azalea-brigadier",
  "azalea-crypto",
  "azalea-world",
]

[profile.release]
debug = true
