[package]
edition = "2021"
name = "azalea-nbt"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = {version = "^0.3.8", features = ["tokio", "zlib", "gzip"]}
async-recursion = "^0.3.2"
byteorder = "^1.4.3"
flate2 = "^1.0.22"
num-derive = "^0.3.3"
num-traits = "^0.2.14"
tokio = "^1.15.0"

[dev-dependencies]
criterion = {version = "^0.3.5", features = ["html_reports", "async_tokio"]}
tokio = {version = "^1.15.0", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread"]}

[profile.release]
lto = true

[profile.bench]
debug = true

[[bench]]
harness = false
name = "my_benchmark"
