[package]
edition = "2021"
name = "azalea-physics"
version = "0.1.0"
description = "Physics for Minecraft entities."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-block = { path = "../azalea-block" }
azalea-core = { path = "../azalea-core" }
azalea-world = { path = "../azalea-world" }

[dev-dependencies]
uuid = "^1.1.2"
