[package]
description = "A port of Mojang's Authlib, except authentication isn't actually implemented yet."
edition = "2021"
license = "MIT"
name = "azalea-auth"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = {path = "../azalea-buf", version = "^0.1.0"}
uuid = "^1.1.2"
