[package]
name = "bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minecraft-client = { path = "../minecraft-client" }
minecraft-protocol = { path = "../minecraft-protocol" }
tokio = "^1.14.0"
